"use client";
import { useCallback, useEffect, useState } from "react";
import { ChevronDown, ChevronUp, Pencil, Plus, Trash2, X } from "lucide-react";
import { useTranslations } from "next-intl";
import { Link } from "@/i18n/navigation";
import { AdminField, AdminSearchPicker, adminButtonClass, adminInputClass } from "@/components/admin/CatalogAdminControls";

type Artist = { id:string; name:string; slug?:string|null; type?:string|null; primary_role?:string|null };
type Credit = { id:string;artist_id:string;role:string;credited_as:string|null;display_order:number|null;position:number|null;metadata:{join_phrase?:string}|null;artists:Artist|null };
const roles=["lead_performer","featured_performer","guest_performer","instrumentalist","vocalist","choir","orchestra","guitar","drums","piano","bass","trumpet","saxophone","trombone","strings","horns","percussion","conductor","producer","engineer","recording_engineer","mixing_engineer","mixing","mastering_engineer","mastering","session_musician","arranger","composer"];

export default function RecordingCreditsManager({recordingId,recordingSlug}:{recordingId:string;recordingSlug:string|null}) {
  const t=useTranslations("admin.recordingCredits"); const [credits,setCredits]=useState<Credit[]>([]); const [loading,setLoading]=useState(false); const [message,setMessage]=useState(""); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<Credit|null>(null); const [artist,setArtist]=useState<Artist|null>(null); const [role,setRole]=useState(roles[0]); const [creditedAs,setCreditedAs]=useState(""); const [joinPhrase,setJoinPhrase]=useState("");
  const load=useCallback(async()=>{setLoading(true);const response=await fetch(`/api/admin/recording-credits?recordingId=${encodeURIComponent(recordingId)}`);const result=await response.json();setLoading(false);if(!response.ok)return setMessage(t("loadFailed"));setCredits(result.credits??[]);},[recordingId,t]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void load();},[load]);
  function begin(credit?:Credit){setEditing(credit??null);setArtist(credit?.artists??null);setRole(credit?.role??roles[0]);setCreditedAs(credit?.credited_as??"");setJoinPhrase(credit?.metadata?.join_phrase??"");setOpen(true);setMessage("");}
  async function save(){if(!artist)return setMessage(t("artistRequired"));setLoading(true);const response=await fetch("/api/admin/recording-credits",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({recordingId,creditId:editing?.id,artistId:artist.id,role,creditedAs,joinPhrase,displayOrder:editing?.display_order??credits.length})});const result=await response.json();setLoading(false);if(!response.ok)return setMessage(result.error==="duplicateCredit"?t("duplicateCredit"):t("saveFailed"));setOpen(false);setMessage(editing?t("updated"):t("added"));await load();}
  async function remove(credit:Credit){if(!window.confirm(t("removeConfirm")))return;const response=await fetch("/api/admin/recording-credits",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({recordingId,creditId:credit.id})});if(response.ok){setMessage(t("removed"));await load();}else setMessage(t("removeFailed"));}
  async function move(index:number,direction:-1|1){const next=index+direction;if(next<0||next>=credits.length)return;const ordered=[...credits];[ordered[index],ordered[next]]=[ordered[next],ordered[index]];setCredits(ordered);const response=await fetch("/api/admin/recording-credits",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({recordingId,creditIds:ordered.map((credit)=>credit.id)})});if(!response.ok){setMessage(t("reorderFailed"));await load();}}
  return <section className="rounded-xl border border-gray-100 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xs uppercase tracking-[0.2em] text-(--color-wikicrimson)">{t("title")}</h2>{recordingSlug&&<Link href={`/songs/${recordingSlug}`} prefetch={false} className="mt-2 inline-flex text-xs text-(--color-flagblue) hover:underline">{t("viewSong")}</Link>}</div><button type="button" onClick={()=>begin()} className={adminButtonClass}><Plus className="mr-2 inline h-4 w-4"/>{t("add")}</button></div>
    {message&&<p className="mt-3 rounded border bg-gray-50 p-2 text-sm">{message}</p>}{loading&&!credits.length?<p className="mt-4 text-sm text-gray-500">{t("loading")}</p>:credits.length?<div className="mt-4 space-y-2">{credits.map((credit,index)=><div key={credit.id} className="grid gap-3 rounded-lg border bg-gray-50 p-3 sm:grid-cols-[1fr_160px_1fr_auto] sm:items-center"><div>{credit.artists?.slug?<Link href={`/artists/${credit.artists.slug}`} prefetch={false} className="font-medium text-(--color-flagblue) hover:underline">{credit.artists.name}</Link>:<span className="font-medium">{credit.artists?.name??t("missingArtist")}</span>}<p className="text-xs text-gray-500">{credit.credited_as||credit.artists?.name}</p></div><span className="text-sm">{t.has(`roles.${credit.role}`)?t(`roles.${credit.role}`):credit.role}</span><span className="text-xs text-gray-500">{credit.metadata?.join_phrase||"—"} · {t("order",{order:index+1})}</span><div className="flex gap-1"><button type="button" disabled={index===0} onClick={()=>void move(index,-1)} aria-label={t("moveUp",{artist:credit.artists?.name??""})} className="rounded p-2 disabled:opacity-30"><ChevronUp className="h-4 w-4"/></button><button type="button" disabled={index===credits.length-1} onClick={()=>void move(index,1)} aria-label={t("moveDown",{artist:credit.artists?.name??""})} className="rounded p-2 disabled:opacity-30"><ChevronDown className="h-4 w-4"/></button><button type="button" onClick={()=>begin(credit)} aria-label={t("editFor",{artist:credit.artists?.name??""})} className="rounded p-2"><Pencil className="h-4 w-4"/></button><button type="button" onClick={()=>void remove(credit)} aria-label={t("removeFor",{artist:credit.artists?.name??""})} className="rounded p-2 text-red-700"><Trash2 className="h-4 w-4"/></button></div></div>)}</div>:<p className="mt-4 rounded-lg border border-dashed bg-gray-50 p-4 text-sm text-gray-500">{t("empty")}</p>}
    {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div role="dialog" aria-modal="true" aria-labelledby="credit-dialog-title" className="w-full max-w-lg rounded-xl bg-white p-6 shadow-xl"><div className="flex justify-between"><h3 id="credit-dialog-title" className="text-lg font-semibold text-(--color-flagblue)">{editing?t("edit"):t("add")}</h3><button type="button" onClick={()=>setOpen(false)} aria-label={t("cancel")}><X/></button></div><div className="mt-5 space-y-4"><AdminSearchPicker label={t("artist")} value={artist?.id??""} displayValue={artist?.name??""} placeholder={t("searchArtist")} endpoint="/api/admin/artists" resultKey="artists" onSelect={(option)=>setArtist({id:option.id,name:option.name??""})} onClear={()=>setArtist(null)}/><AdminField label={t("role")}><select value={role} onChange={(event)=>setRole(event.target.value)} className={adminInputClass}>{roles.map((value)=><option key={value} value={value}>{t(`roles.${value}`)}</option>)}</select></AdminField><AdminField label={t("creditedAs")}><input maxLength={200} value={creditedAs} onChange={(event)=>setCreditedAs(event.target.value)} className={adminInputClass}/><p className="mt-1 text-xs leading-5 text-gray-500">{t("creditedAsHelp")}</p></AdminField><AdminField label={t("joinPhrase")}><input maxLength={40} value={joinPhrase} onChange={(event)=>setJoinPhrase(event.target.value)} className={adminInputClass}/><p className="mt-1 text-xs leading-5 text-gray-500">{t("joinPhraseHelp")}</p></AdminField><div className="flex gap-2"><button type="button" disabled={loading} onClick={()=>void save()} className={adminButtonClass}>{t("save")}</button><button type="button" onClick={()=>setOpen(false)} className="rounded-lg border px-5 py-3 text-xs uppercase">{t("cancel")}</button></div></div></div></div>}
  </section>;
}
