BEGIN;

-- Revierte 20260908009500_clean_redundant_aliases.sql.
-- Devuelve a cada una de las 207 filas su array de alias completo.

UPDATE artists SET aliases = ARRAY['Ada Betsabe']::text[] WHERE slug = 'ada-betsabe';
UPDATE artists SET aliases = ARRAY['Adalgisa Pantaleón', 'Adalgisa Pantaleon']::text[] WHERE slug = 'adalgisa-pantaleon';
UPDATE artists SET aliases = ARRAY['Adriel sfx']::text[] WHERE slug = 'adriel-sfx';
UPDATE artists SET aliases = ARRAY['El Bachatú del Merengue', 'Rey del Merengue Electrónico', 'Rompe Plantica', 'Enmanuel Jiménez']::text[] WHERE slug = 'ala-jaza';
UPDATE artists SET aliases = ARRAY['El Negrito del Batey', 'Alberto Amancio Beltrán']::text[] WHERE slug = 'alberto-beltran';
UPDATE artists SET aliases = ARRAY['Felipe Alejandro Linares Jiménez', 'Felipe A. Linares', 'Alex Linares']::text[] WHERE slug = 'alex-linares';
UPDATE artists SET aliases = ARRAY['La Reina de la Bachata', 'Alexandra', 'Alexandra Cabrera de la Cruz']::text[] WHERE slug = 'alexandra-queen';
UPDATE artists SET aliases = ARRAY['Agapito Decena Geraldo', 'Allendy Decena']::text[] WHERE slug = 'allendy';
UPDATE artists SET aliases = ARRAY['Flow Nastry', 'Alnastry Valentín']::text[] WHERE slug = 'alnastry';
UPDATE artists SET aliases = ARRAY['Amarfis Aquino']::text[] WHERE slug = 'amarfis';
UPDATE artists SET aliases = ARRAY['Anaís Martínez']::text[] WHERE slug = 'anais';
UPDATE artists SET aliases = ARRAY['Ander Antonio Bock Sánchez', 'AnderBock']::text[] WHERE slug = 'ander-bock';
UPDATE artists SET aliases = ARRAY['Angel Brown', 'Ángel Brown Abreu']::text[] WHERE slug = 'angel-brown';
UPDATE artists SET aliases = ARRAY['Conjunto Típico Cibaeño', 'Ángel Salvador Viloria']::text[] WHERE slug = 'angel-viloria-y-su-conjunto-tipico-cibaeno';
UPDATE artists SET aliases = ARRAY['Newton Aníbal de Peña']::text[] WHERE slug = 'anibal-de-pena';
UPDATE artists SET aliases = ARRAY['Anmily Brown', 'ANMILY']::text[] WHERE slug = 'anmily';
UPDATE artists SET aliases = ARRAY['El Sentimental', 'Antonio Jiménez', 'El Kínder', 'Anthony Rios']::text[] WHERE slug = 'anthony-rios';
UPDATE artists SET aliases = ARRAY['Ari', 'Arianna Isabel Puello Pereyra']::text[] WHERE slug = 'arianna-puello';
UPDATE artists SET aliases = ARRAY['Asdrúbar Báez']::text[] WHERE slug = 'asdrubar';
UPDATE artists SET aliases = ARRAY['Francisco Alberto Sosa Paredes']::text[] WHERE slug = 'bertico-sosa';
UPDATE artists SET aliases = ARRAY['El Maestro Bonny Cepeda', 'Fernando Cruz', 'El Maestro Joven del Merengue', 'El Inestable', 'Fernando Antonio Cruz Paz']::text[] WHERE slug = 'bonny-cepeda';
UPDATE artists SET aliases = ARRAY['Bryan Misael García Brito']::text[] WHERE slug = 'brayan-booz';
UPDATE artists SET aliases = ARRAY['El Ideologo', 'Josué Abel Guzmán Cruz', 'Josué Guzmán', 'El Ideologo BS']::text[] WHERE slug = 'bs-el-ideologo';
UPDATE artists SET aliases = ARRAY['Rafael Bullumba Landestoy', 'Pedro Rafael Landestoy Duluc']::text[] WHERE slug = 'bullumba-landestoy';
UPDATE artists SET aliases = ARRAY['Camilo Marichal']::text[] WHERE slug = 'calacote';
UPDATE artists SET aliases = ARRAY['Greilyn Candelario']::text[] WHERE slug = 'candelario';
UPDATE artists SET aliases = ARRAY['Canoto', 'Conceptual', 'Arístides Ortiz Luis']::text[] WHERE slug = 'canoto';
UPDATE artists SET aliases = ARRAY['Carlos Alfredo', 'Carlos Alfredo Fatule Guerrero']::text[] WHERE slug = 'carlos-alfredo-fatule';
UPDATE artists SET aliases = ARRAY['José Luis Green']::text[] WHERE slug = 'chelion';
UPDATE artists SET aliases = ARRAY['La Tercera Brigada', 'Chery Jimenez y su Tercera Brigada']::text[] WHERE slug = 'chery-jimenez-y-su-tercera-brigada';
UPDATE artists SET aliases = ARRAY['Chichi Peralta', 'Pedro René Peralta Soto']::text[] WHERE slug = 'chichi-peralta';
UPDATE artists SET aliases = ARRAY['Chiky Bom Bom "La Pantera"', 'Chikybombom La Pantera', 'La Pantera', 'Lissette Eduardo Cleto']::text[] WHERE slug = 'chiky-bombom-la-pantera';
UPDATE artists SET aliases = ARRAY['Coral', 'Coral Laluz']::text[] WHERE slug = 'coral-la-luz';
UPDATE artists SET aliases = ARRAY['Cromo La X', 'Martín Rodríguez Vicente']::text[] WHERE slug = 'cromo-x';
UPDATE artists SET aliases = ARRAY['Francisco Alberto Simo Damiron', 'El Rey del Piano Merengue', 'Los Alegres Tres']::text[] WHERE slug = 'damiron';
UPDATE artists SET aliases = ARRAY['Didí Hernández']::text[] WHERE slug = 'didi-hernandez';
UPDATE artists SET aliases = ARRAY['DJADONI', 'DJ Adoni', 'Julio Adoni Gross', 'Julio Adonis Gross', 'Julio Adonis Gross Gonzalez']::text[] WHERE slug = 'dj-adoni';
UPDATE artists SET aliases = ARRAY['El Gigante', 'Aneudy Reynoso', 'DJ Aneudy El Gigante']::text[] WHERE slug = 'dj-aneudy';
UPDATE artists SET aliases = ARRAY['DJ Arelis Hot', 'Arelis Hernández Gómez']::text[] WHERE slug = 'dj-arelis-hot';
UPDATE artists SET aliases = ARRAY['DJ Joe', 'DJ Joe Catador', 'Joel Tapia']::text[] WHERE slug = 'dj-joe-catador';
UPDATE artists SET aliases = ARRAY['DJ Plano']::text[] WHERE slug = 'dj-plano';
UPDATE artists SET aliases = ARRAY['Urbani Mota Cedeño', 'Urba y Rome', 'Los Evo Jedis', 'Los Jedis']::text[] WHERE slug = 'dj-urba';
UPDATE artists SET aliases = ARRAY['Yeifry Sanchez', 'El Nene']::text[] WHERE slug = 'donaty';
UPDATE artists SET aliases = ARRAY['Draconum Oth Neghor', 'Frank Sánchez']::text[] WHERE slug = 'draconum-oth';
UPDATE artists SET aliases = ARRAY['Jose Duluc', 'Duluc Folclor']::text[] WHERE slug = 'duluc';
UPDATE artists SET aliases = ARRAY['Eddy Bastian', 'Eddie Bastián', 'Eduardo Bastian', 'El Único', 'Eddy El Único', 'Eddie Bastian y su Orquesta', 'Eduardo Bastian y su Orquesta', 'Eddie Bastian And His Swinging Band', 'Eddie Bastian']::text[] WHERE slug = 'eddie-bastian';
UPDATE artists SET aliases = ARRAY['El Alfa El Jefe', 'Emanuel Herrera Batista']::text[] WHERE slug = 'el-alfa';
UPDATE artists SET aliases = ARRAY['Edward Bello Pou', 'El Cata Mundial']::text[] WHERE slug = 'el-cata';
UPDATE artists SET aliases = ARRAY['Jose Gabriel Garcia', 'El Canta Lindo', 'La Artilleria']::text[] WHERE slug = 'el-jeffrey';
UPDATE artists SET aliases = ARRAY['El Mayor', 'Emmanuel Reyes']::text[] WHERE slug = 'el-mayor-clasico';
UPDATE artists SET aliases = ARRAY['Esteban Philippe', 'Philippe', 'Fhilippe']::text[] WHERE slug = 'el-philippe';
UPDATE artists SET aliases = ARRAY['Enmanuel García Batista', 'El Rubito']::text[] WHERE slug = 'el-rubio-acordeon';
UPDATE artists SET aliases = ARRAY['Eduardo José Acevedo Cabrera']::text[] WHERE slug = 'el-varon-de-la-bachata';
UPDATE artists SET aliases = ARRAY['Andy Mora']::text[] WHERE slug = 'emetede';
UPDATE artists SET aliases = ARRAY['Enrique de Marchena']::text[] WHERE slug = 'enrique-de-marchena';
UPDATE artists SET aliases = ARRAY['Epico Gelato']::text[] WHERE slug = 'epico-gelato';
UPDATE artists SET aliases = ARRAY['Elmer Abreu Suriel']::text[] WHERE slug = 'esme';
UPDATE artists SET aliases = ARRAY['El Niche', 'Fausto Ramon Sepulveda']::text[] WHERE slug = 'fausto-rey';
UPDATE artists SET aliases = ARRAY['Carlos Flores']::text[] WHERE slug = 'flow-28';
UPDATE artists SET aliases = ARRAY['La Super F', 'Israel Domingo Rodríguez de la Cruz']::text[] WHERE slug = 'fortuna-la-super-f';
UPDATE artists SET aliases = ARRAY['GDA', 'Delvi Antonio Abreu Martínez']::text[] WHERE slug = 'gda-el-unico';
UPDATE artists SET aliases = ARRAY['GhettoSPM', 'Axel Rafael Quezada Fulgencio']::text[] WHERE slug = 'ghetto';
UPDATE artists SET aliases = ARRAY['El Torito', 'Hector Acosta y Su Orquesta', 'Los Toros Band', 'Hector Elpidio Acosta Restituyo']::text[] WHERE slug = 'hector-acosta-el-torito';
UPDATE artists SET aliases = ARRAY['Henry Santos Jeter', 'Aventura']::text[] WHERE slug = 'henry-santos';
UPDATE artists SET aliases = ARRAY['INKA']::text[] WHERE slug = 'inka';
UPDATE artists SET aliases = ARRAY['Isabelle', 'Isabelle Valdéz', 'Isabelle Valdéz Santana', 'Isabel Valdez']::text[] WHERE slug = 'isabelle-valdez';
UPDATE artists SET aliases = ARRAY['Jacinto Gimbernard Pellerano']::text[] WHERE slug = 'jacinto-gimbernard';
UPDATE artists SET aliases = ARRAY['Juan de Dios Ventura Flores', 'Jandy Ventura el Legado', 'Los Potros']::text[] WHERE slug = 'jandy-ventura';
UPDATE artists SET aliases = ARRAY['El Criminal', 'Jean Carlos Nami Encarnación']::text[] WHERE slug = 'jankobow';
UPDATE artists SET aliases = ARRAY['Yefri Mecredy de la Cruz']::text[] WHERE slug = 'jay-miky-flow';
UPDATE artists SET aliases = ARRAY['Jon Clasic', 'Juan Carlos Cabrera']::text[] WHERE slug = 'jc';
UPDATE artists SET aliases = ARRAY['Jose Manuel Almonte', 'Joa']::text[] WHERE slug = 'joa-el-super-mc';
UPDATE artists SET aliases = ARRAY['Jordan Joel Mateo Green']::text[] WHERE slug = 'jordan-mateo';
UPDATE artists SET aliases = ARRAY['Jorge Luis Rosario Rodriguez']::text[] WHERE slug = 'jorge-luis-rosario-rodriguez';
UPDATE artists SET aliases = ARRAY['Jose Gabriel Guaba', 'Jose El Calvo y Su Conjunto Tipico']::text[] WHERE slug = 'jose-el-calvo';
UPDATE artists SET aliases = ARRAY['Jose Luis Hernandez Moreno']::text[] WHERE slug = 'jose-luis-hernandez-moreno';
UPDATE artists SET aliases = ARRAY['La Banda Gorda', 'Jose Virgilio Peña Suazo']::text[] WHERE slug = 'jose-pena-suazo-y-la-banda-gorda';
UPDATE artists SET aliases = ARRAY['Juan Luis Guerra Seijas', 'Juan Luis Guerra & 440', '440']::text[] WHERE slug = 'juan-luis-guerra';
UPDATE artists SET aliases = ARRAY['La Reina del Mambo', 'Juliana Ynurika O''neal Brito']::text[] WHERE slug = 'juliana-o-neal';
UPDATE artists SET aliases = ARRAY['Rasputin', 'July Mateo Rasputin', 'Rasputín', 'El Monje']::text[] WHERE slug = 'july-mateo-rasputin';
UPDATE artists SET aliases = ARRAY['Milton Cabrera']::text[] WHERE slug = 'junior-cabrera';
UPDATE artists SET aliases = ARRAY['Kalimete La Fórmula', 'Ramfis Reyes']::text[] WHERE slug = 'kalimete';
UPDATE artists SET aliases = ARRAY['Karlos Rose', 'K. Rose', 'Carlos De La Rosa']::text[] WHERE slug = 'karlos-rose';
UPDATE artists SET aliases = ARRAY['Kiko El Crazy', 'Kiko El Creizy']::text[] WHERE slug = 'kiko-el-crazy';
UPDATE artists SET aliases = ARRAY['La BABY']::text[] WHERE slug = 'la-baby';
UPDATE artists SET aliases = ARRAY['Cristhofher Reyes Rodríguez']::text[] WHERE slug = 'la-fiera-tipica';
UPDATE artists SET aliases = ARRAY['La Noe', 'Noemí Martínez']::text[] WHERE slug = 'la-noe-aposento-alto';
UPDATE artists SET aliases = ARRAY['Rosa María Pineda Aguavivas']::text[] WHERE slug = 'la-ross-maria';
UPDATE artists SET aliases = ARRAY['Leticia Pelliccione']::text[] WHERE slug = 'leton-pe';
UPDATE artists SET aliases = ARRAY['La Pastora', 'Lisbet Margarita Plata Parra', 'Lizzy']::text[] WHERE slug = 'lizzy-parra';
UPDATE artists SET aliases = ARRAY['Lors', 'Osiris Rincón', 'LorsRD']::text[] WHERE slug = 'lors-el-prieto';
UPDATE artists SET aliases = ARRAY['Jorge Luis Mena Reynoso', 'Luis Carácter']::text[] WHERE slug = 'luis-caracter';
UPDATE artists SET aliases = ARRAY['El Terror', 'Luis Terror Dias', 'Transporte Urbano', 'Luis Días Portorreal', 'El Terror', 'Luis Díaz', 'Luis Dias']::text[] WHERE slug = 'luis-terror-dias';
UPDATE artists SET aliases = ARRAY['Luny Tunes']::text[] WHERE slug = 'luny-tunes';
UPDATE artists SET aliases = ARRAY['Luis Bienvenido Gómez Luciano', 'Luis Bienvenido Gómez', 'Luis Gómez']::text[] WHERE slug = 'luys-bien';
UPDATE artists SET aliases = ARRAY['Maffio', 'Carlos Ariel Peralta Mendoza']::text[] WHERE slug = 'maffio';
UPDATE artists SET aliases = ARRAY['mamajuana']::text[] WHERE slug = 'mamajuana';
UPDATE artists SET aliases = ARRAY['Manny Cruz', 'Emmanuel Cruz Sánchez']::text[] WHERE slug = 'manny-cruz';
UPDATE artists SET aliases = ARRAY['Enmanuel Castillo']::text[] WHERE slug = 'manny-manz';
UPDATE artists SET aliases = ARRAY['Manolé y la Banda del Truco']::text[] WHERE slug = 'manole-y-la-banda-del-truco';
UPDATE artists SET aliases = ARRAY['Manuel Jiménez']::text[] WHERE slug = 'manuel-jimenez';
UPDATE artists SET aliases = ARRAY['Manuel Miller', 'DJ Miller', 'DJ Mastermix', 'Manuel de Jesús Díaz Miller']::text[] WHERE slug = 'manuel-miller';
UPDATE artists SET aliases = ARRAY['Manuel Sánchez Acosta']::text[] WHERE slug = 'manuel-sanchez-acosta';
UPDATE artists SET aliases = ARRAY['Manuel Simó']::text[] WHERE slug = 'manuel-simo';
UPDATE artists SET aliases = ARRAY['Manuel Troncoso']::text[] WHERE slug = 'manuel-troncoso';
UPDATE artists SET aliases = ARRAY['Manyee Audio']::text[] WHERE slug = 'manyee-audio';
UPDATE artists SET aliases = ARRAY['Marco Hernández Taveras']::text[] WHERE slug = 'marco-hernandez';
UPDATE artists SET aliases = ARRAY['Marcos Andres Peguero Familia']::text[] WHERE slug = 'marcos-andres-peguero-familia';
UPDATE artists SET aliases = ARRAY['Marcos Yaroide', 'Marcos Yaroide Mejía Rambalde']::text[] WHERE slug = 'marcos-yaroide';
UPDATE artists SET aliases = ARRAY['Mariangel']::text[] WHERE slug = 'mariangel';
UPDATE artists SET aliases = ARRAY['Maridalia Hernández', 'Maridalia Hernández Morel']::text[] WHERE slug = 'maridalia-hernandez';
UPDATE artists SET aliases = ARRAY['Mariela Pérez', 'Ministerios Mariela Valdez']::text[] WHERE slug = 'mariela-valdez';
UPDATE artists SET aliases = ARRAY['Marielle Hazlo']::text[] WHERE slug = 'marielle-hazlo';
UPDATE artists SET aliases = ARRAY['Esteban Marinito Pérez', 'El Padre de la Bachata de Amargue', 'El Bachatero del Pueblo']::text[] WHERE slug = 'marino-perez';
UPDATE artists SET aliases = ARRAY['Mark Burdier']::text[] WHERE slug = 'mark-b';
UPDATE artists SET aliases = ARRAY['Martín Valoy']::text[] WHERE slug = 'martin-valoy';
UPDATE artists SET aliases = ARRAY['Mc Wayne']::text[] WHERE slug = 'mc-wayne';
UPDATE artists SET aliases = ARRAY['Isaac Elías Sánchez Camilo', 'La M Mayúscula']::text[] WHERE slug = 'mecal';
UPDATE artists SET aliases = ARRAY['Pablo Alcántara']::text[] WHERE slug = 'mediopicky';
UPDATE artists SET aliases = ARRAY['Medusa']::text[] WHERE slug = 'medusa';
UPDATE artists SET aliases = ARRAY['Melida Rodriguez']::text[] WHERE slug = 'melida-rodriguez';
UPDATE artists SET aliases = ARRAY['Melony Redondo', 'La Mamá del Rap', 'La Mermelada']::text[] WHERE slug = 'melymel';
UPDATE artists SET aliases = ARRAY['Memín', 'El Sucesor', 'Giovanny Belliard']::text[] WHERE slug = 'memin';
UPDATE artists SET aliases = ARRAY['Messiah', 'El Artista', 'Young Messi', 'El Monito']::text[] WHERE slug = 'messiah';
UPDATE artists SET aliases = ARRAY['Michel Batista', 'El Buenón']::text[] WHERE slug = 'michel-el-buenon';
UPDATE artists SET aliases = ARRAY['Mickey Dastinz']::text[] WHERE slug = 'mickey-dastinz';
UPDATE artists SET aliases = ARRAY['Mickey Taveras', 'Miguel Vinicio Almánzar Taveras']::text[] WHERE slug = 'mickey-taveras';
UPDATE artists SET aliases = ARRAY['Michael Luis López']::text[] WHERE slug = 'mike-el-beta';
UPDATE artists SET aliases = ARRAY['Milly Quezada', 'La Reina del Merengue', 'Queen of Merengue', 'Milagros del Rosario Quezada Borbón']::text[] WHERE slug = 'milly-quezada';
UPDATE artists SET aliases = ARRAY['Miriam Aracelis Cruz Ramírez', 'La Diva del Merengue']::text[] WHERE slug = 'miriam-cruz';
UPDATE artists SET aliases = ARRAY['Miriam y las Chicas', 'Míriam Cruz y Las Chicas']::text[] WHERE slug = 'miriam-y-las-chicas';
UPDATE artists SET aliases = ARRAY['Misael Josué Rosario Mena']::text[] WHERE slug = 'misael-j';
UPDATE artists SET aliases = ARRAY['Monchy', 'Ramón Rijo']::text[] WHERE slug = 'monchy';
UPDATE artists SET aliases = ARRAY['Monchy & Alexandra', 'Monchy y Alexandra']::text[] WHERE slug = 'monchy-alexandra';
UPDATE artists SET aliases = ARRAY['Monchy & Nathalia']::text[] WHERE slug = 'monchy-nathalia';
UPDATE artists SET aliases = ARRAY['MonSanto']::text[] WHERE slug = 'monsanto';
UPDATE artists SET aliases = ARRAY['Morbid']::text[] WHERE slug = 'morbid';
UPDATE artists SET aliases = ARRAY['MÓRIA']::text[] WHERE slug = 'moria';
UPDATE artists SET aliases = ARRAY['MR. Yeison']::text[] WHERE slug = 'mr-yeison';
UPDATE artists SET aliases = ARRAY['Mula']::text[] WHERE slug = 'mula';
UPDATE artists SET aliases = ARRAY['Rafael Edmundo Espinal Hernández']::text[] WHERE slug = 'mundito-espinal';
UPDATE artists SET aliases = ARRAY['Musicólogo The Libro', 'Musicólogo']::text[] WHERE slug = 'musicologo-the-libro';
UPDATE artists SET aliases = ARRAY['Musiquito']::text[] WHERE slug = 'musiquito';
UPDATE artists SET aliases = ARRAY['N o R M a L', 'Gabriel Ernesto López Valdez']::text[] WHERE slug = 'n-o-r-m-a-l';
UPDATE artists SET aliases = ARRAY['María Saray Amancio']::text[] WHERE slug = 'nancy-amancio';
UPDATE artists SET aliases = ARRAY['Natán el Profeta', 'Natanael Philippe']::text[] WHERE slug = 'natan-el-profeta';
UPDATE artists SET aliases = ARRAY['Necro']::text[] WHERE slug = 'necro';
UPDATE artists SET aliases = ARRAY['Negrito Chapuseaux', 'El Negrito Chapuseaux', 'José Ernesto Chapuseaux']::text[] WHERE slug = 'negrito-chapuseaux';
UPDATE artists SET aliases = ARRAY['Nelson Mendoza Batista', 'Nelson de la Olla y La Banda Chula']::text[] WHERE slug = 'nelson-de-la-olla';
UPDATE artists SET aliases = ARRAY['Alberto Nicolás Aponte Castillo', 'El Maestro del Género Urbano']::text[] WHERE slug = 'nico-clinico';
UPDATE artists SET aliases = ARRAY['Niní Cáffaro', 'Rey de los Festivales', 'Erasmo Alfonso Cáffaro Durán']::text[] WHERE slug = 'nini-caffaro';
UPDATE artists SET aliases = ARRAY['Yeifry Severino de la Rosa']::text[] WHERE slug = 'nino-freestyle';
UPDATE artists SET aliases = ARRAY['Ninón Lapeiretta de Brouwer']::text[] WHERE slug = 'ninon-lapeiretta-de-brouwer';
UPDATE artists SET aliases = ARRAY['NJ Melody']::text[] WHERE slug = 'nj-melody';
UPDATE artists SET aliases = ARRAY['Enmanuel Cuello Reynoso', 'Nominal']::text[] WHERE slug = 'nmnl';
UPDATE artists SET aliases = ARRAY['OG Black', 'Adolfo Ramírez Bruno', 'El Francotirador']::text[] WHERE slug = 'o-g-black';
UPDATE artists SET aliases = ARRAY['Omega "El Fuerte"', 'Antonio Peter de la Rosa', 'El Fuerte']::text[] WHERE slug = 'omega';
UPDATE artists SET aliases = ARRAY['Oscar La Entonación', 'Oscar Enrique Socías Santana']::text[] WHERE slug = 'oscar-dominic';
UPDATE artists SET aliases = ARRAY['Pamela Lebrón', 'La Lebrón']::text[] WHERE slug = 'pamela-lebron';
UPDATE artists SET aliases = ARRAY['El Rey De La República', 'Robert José de León Sánchez']::text[] WHERE slug = 'papi-sanchez';
UPDATE artists SET aliases = ARRAY['Johan Pavel Domínguez']::text[] WHERE slug = 'paramba';
UPDATE artists SET aliases = ARRAY['Pedro Samuel Rodríguez-Reyes', 'P. S. Rodz']::text[] WHERE slug = 'pedro-samuel-rodriguez';
UPDATE artists SET aliases = ARRAY['Pedro Julio Pérez Metivier']::text[] WHERE slug = 'peter-metivier';
UPDATE artists SET aliases = ARRAY['Pierre Carbuccia Abbott', 'Juracán']::text[] WHERE slug = 'pierre-carbuccia';
UPDATE artists SET aliases = ARRAY['Jeyson Rey Piñeiro Azcona']::text[] WHERE slug = 'profeta-lirical';
UPDATE artists SET aliases = ARRAY['Púyalo Pantera', 'Jarlin José Beltre Lara']::text[] WHERE slug = 'puyalo-pantera';
UPDATE artists SET aliases = ARRAY['Químico', 'Jesús Jiménez']::text[] WHERE slug = 'quimico-ultra-mega';
UPDATE artists SET aliases = ARRAY['Silvestre Colón Casilla']::text[] WHERE slug = 'raphy-colon';
UPDATE artists SET aliases = ARRAY['La Estrella del Merengue Típico', 'La Fiera', 'La Insuperable', 'Raquel Arias Jiménez']::text[] WHERE slug = 'raquel-arias';
UPDATE artists SET aliases = ARRAY['Raulin Rodriguez', 'El Cacique', 'El Cacique del Amargue', 'Raulín Marte Rodríguez']::text[] WHERE slug = 'raulin-rodriguez';
UPDATE artists SET aliases = ARRAY['Oh Man', 'La Resistencia', 'MC1615', 'Willy Cruz', 'Willy González Cruz', 'GC Willy']::text[] WHERE slug = 'redimi2';
UPDATE artists SET aliases = ARRAY['Wrisberg René De León', 'Rene De Leon Vanterpool']::text[] WHERE slug = 'rene-de-leon-vanterpool';
UPDATE artists SET aliases = ARRAY['Herminio Ricardo Rico', 'Ricardo Rico y su Conjunto Los Típicos Dominicanos']::text[] WHERE slug = 'ricardo-rico';
UPDATE artists SET aliases = ARRAY['José Miguel Guzmán Sandoval']::text[] WHERE slug = 'ricky-webber';
UPDATE artists SET aliases = ARRAY['Benigno Ricardo López', 'Rico López y su Orquesta']::text[] WHERE slug = 'rico-lopez';
UPDATE artists SET aliases = ARRAY['Roger Zayas']::text[] WHERE slug = 'roger-zayas-bazan';
UPDATE artists SET aliases = ARRAY['Rosángela', 'Rosangela Abreu Crespo']::text[] WHERE slug = 'rosangela-abreu';
UPDATE artists SET aliases = ARRAY['Rubinsky', 'Manuel Enrique Núñez Espinoza']::text[] WHERE slug = 'rubinsky-rbk';
UPDATE artists SET aliases = ARRAY['DJ Sammy', 'Sammy the Greatest', 'Samuel Dilone Castillo']::text[] WHERE slug = 'sammy-the-greatest';
UPDATE artists SET aliases = ARRAY['Sandy', 'Sandy Carriello', 'Sandy A. Carriello']::text[] WHERE slug = 'sandy-mc';
UPDATE artists SET aliases = ARRAY['Salvador Reyes Pichardo']::text[] WHERE slug = 'sandy-reyes';
UPDATE artists SET aliases = ARRAY['Rayniel Santana', 'Santana Official']::text[] WHERE slug = 'santana';
UPDATE artists SET aliases = ARRAY['Jorge Shamir Massih']::text[] WHERE slug = 'shamir-massih';
UPDATE artists SET aliases = ARRAY['Sharlene Taulé', 'Sharlene Taulé Ponciano']::text[] WHERE slug = 'sharlene';
UPDATE artists SET aliases = ARRAY['Shecka', 'Fransheska Felicia Sánchez']::text[] WHERE slug = 'shecka-sanchez';
UPDATE artists SET aliases = ARRAY['Skeem El Conde', 'Lenin Arias']::text[] WHERE slug = 'skeem';
UPDATE artists SET aliases = ARRAY['Marcos Peralta']::text[] WHERE slug = 'snova';
UPDATE artists SET aliases = ARRAY['Franklin Pérez de los Santos', 'Sr Perez', 'Franklin Pérez']::text[] WHERE slug = 'sr-perez';
UPDATE artists SET aliases = ARRAY['Steven Domínguez Carmona']::text[] WHERE slug = 't-y-s';
UPDATE artists SET aliases = ARRAY['TangoWhiskyMan', 'Tangowhiskyman', 'TWM']::text[] WHERE slug = 'tangowhiskyman';
UPDATE artists SET aliases = ARRAY['El Solterito del Este', 'El Macho de la Bachata', 'Basilio Berroa']::text[] WHERE slug = 'tony-berroa';
UPDATE artists SET aliases = ARRAY['Kuky', 'Felipe Antonio Sepúlveda Caraballo']::text[] WHERE slug = 'tony-seval';
UPDATE artists SET aliases = ARRAY['Caonabo Enrique Mesa Ureña', 'Tóxic Crow']::text[] WHERE slug = 'toxic-crow';
UPDATE artists SET aliases = ARRAY['Víctor Cabrera']::text[] WHERE slug = 'tunes';
UPDATE artists SET aliases = ARRAY['Vakero', 'El Vakero', 'Manuel Varet Marte']::text[] WHERE slug = 'vakero';
UPDATE artists SET aliases = ARRAY['Valeria']::text[] WHERE slug = 'valeria-la-mujer';
UPDATE artists SET aliases = ARRAY['Vicente Mercedes Payano']::text[] WHERE slug = 'vicente-mercedes';
UPDATE artists SET aliases = ARRAY['Víctor Irizarry']::text[] WHERE slug = 'victor-irizarry-y-su-orquesta';
UPDATE artists SET aliases = ARRAY['Omar Sánchez']::text[] WHERE slug = 'vizkel';
UPDATE artists SET aliases = ARRAY['Voz A Voz']::text[] WHERE slug = 'voz-a-voz';
UPDATE artists SET aliases = ARRAY['WTA', 'Los Taínos', 'Whitest Taíno Alive']::text[] WHERE slug = 'whitest-taino-alive';
UPDATE artists SET aliases = ARRAY['Wilmelia Soto']::text[] WHERE slug = 'wilmelia';
UPDATE artists SET aliases = ARRAY['Yailín la Más Viral', 'Jorgina Guillermo Díaz']::text[] WHERE slug = 'yailin-la-mas-viral';
UPDATE artists SET aliases = ARRAY['Yamilka Del Rosario Aristy']::text[] WHERE slug = 'yamilka';
UPDATE artists SET aliases = ARRAY['Jennifher Danielle Heredia']::text[] WHERE slug = 'yeidy-eish';
UPDATE artists SET aliases = ARRAY['Yomel', 'Yomel El Meloso']::text[] WHERE slug = 'yomel-el-meloso';
UPDATE artists SET aliases = ARRAY['Zacarías Ferreira de la Cruz', 'La Voz de la Ternura']::text[] WHERE slug = 'zacarias-ferreira';

COMMIT;
