BEGIN;

-- Revierte 20260916011300_rewrite_cheche_abreu_biography.sql con los documentos y campos previos.

DELETE FROM editorial_entity_references WHERE editorial_document_id IN (
  SELECT d.id FROM editorial_documents d JOIN artists a ON a.id = d.owner_artist_id
   WHERE a.slug = 'cheche-abreu' AND d.document_type = 'artist_biography');
DELETE FROM editorial_documents WHERE owner_artist_id = (SELECT id FROM artists WHERE slug = 'cheche-abreu') AND document_type = 'artist_biography';
INSERT INTO editorial_documents (document_type, locale, schema_version, document, status, owner_artist_id, revision)
SELECT 'artist_biography', 'es', 1, '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"José Abreu Vargas «Cheché», «La Negra Pola», Nació el 26 de julio del año 1939 en Manoguayabo, Santo Domingo, capital de la República Dominicana. Legendario Cantante, Compositor Guitarrista y Director de orquesta, de los más trascendentales de Quisqueya. En el año 1961 comienza a incursionar en el arte de la música, formando «El Sexteto Manoguayabo», este nombre se debió que todo sus integrantes eran oriundos de esta comunidad, entre ellos estaban Pedro Germán Benítez (Guitarra Segunda), Cheché Abreu (Tresista y director del grupo), Pablo Abreu (Bajista), Gregorio Germán (Bongosero), Eligio del Pozo (Maraca y Guira) y Pablo Santos Rodríguez -Chichón- (Trompeta). El grupo debutó profesionalmente el 25 de diciembre en 1963 en la «Gran Parada Bar» lugar de esparcimiento localizado en Manoguayabo, para ese entonces. El Sexteto de Manoguayabo seguía firme y adquiriendo popularidad, luego aumentó su número de seis miembros a trece, convirtiéndose en a la agrupación «Cheché Abreu y sus Colosos», esto ocurre en octubre del año 1966. En el año de 1970 comienzan su proceso de grabación, comenzaron a grabar en el Salón Mozart, a cambio de promoción; luego en la Dixie Records, en Miami, en el cual grabaron 5 LP; también a cambio de promoción; luego grabaron 4 LP a Mateo San Martin de la Cubaney, a cambio también de promoción. Ninguna de estas Empresas promocionaron el grupo en la República Dominicana hasta que en el año 1978 comienzan a grabar para «La Guarachita» la cual, aunque a cambio de promoción también, dio a conocer la orquesta a nivel mundial, viajando la agrupación, llevando el merengue y El Mangué, ritmo creado por Cheché Abreu, en toda América y Europa. Por nuestra música, el grupo de Cheche Abreu y sus colosos fue el primer grupo de República Dominicana de llenar el Madison Square Garden (USA). El grupo se presento en todos los Estados Unidos con el tema «La Negra Pola», también tuvo éxitos con el tema en Venezuela, España, Puerto Rico, Haití, Aruba, Curazao, Donaire, San Martin y muchos países más de Centro y Sur América. Luego de cumplido el contrato con «La Guarachita», la agrupación entra a grabar con la casa Combo Records, de Raffi Car.","type":"text"}]}]}'::jsonb, 'published', id, 2 FROM artists WHERE slug = 'cheche-abreu';
UPDATE artists SET bio_en = NULL, bio_es = 'José Abreu Vargas «Cheché», «La Negra Pola», Nació el 26 de julio del año 1939 en Manoguayabo, Santo Domingo, capital de la República Dominicana. Legendario Cantante, Compositor Guitarrista y Director de orquesta, de los más trascendentales de Quisqueya. En el año 1961 comienza a incursionar en el arte de la música, formando «El Sexteto Manoguayabo», este nombre se debió que todo sus integrantes eran oriundos de esta comunidad, entre ellos estaban Pedro Germán Benítez (Guitarra Segunda), Cheché Abreu (Tresista y director del grupo), Pablo Abreu (Bajista), Gregorio Germán (Bongosero), Eligio del Pozo (Maraca y Guira) y Pablo Santos Rodríguez -Chichón- (Trompeta). El grupo debutó profesionalmente el 25 de diciembre en 1963 en la «Gran Parada Bar» lugar de esparcimiento localizado en Manoguayabo, para ese entonces. El Sexteto de Manoguayabo seguía firme y adquiriendo popularidad, luego aumentó su número de seis miembros a trece, convirtiéndose en a la agrupación «Cheché Abreu y sus Colosos», esto ocurre en octubre del año 1966. En el año de 1970 comienzan su proceso de grabación, comenzaron a grabar en el Salón Mozart, a cambio de promoción; luego en la Dixie Records, en Miami, en el cual grabaron 5 LP; también a cambio de promoción; luego grabaron 4 LP a Mateo San Martin de la Cubaney, a cambio también de promoción. Ninguna de estas Empresas promocionaron el grupo en la República Dominicana hasta que en el año 1978 comienzan a grabar para «La Guarachita» la cual, aunque a cambio de promoción también, dio a conocer la orquesta a nivel mundial, viajando la agrupación, llevando el merengue y El Mangué, ritmo creado por Cheché Abreu, en toda América y Europa. Por nuestra música, el grupo de Cheche Abreu y sus colosos fue el primer grupo de República Dominicana de llenar el Madison Square Garden (USA). El grupo se presento en todos los Estados Unidos con el tema «La Negra Pola», también tuvo éxitos con el tema en Venezuela, España, Puerto Rico, Haití, Aruba, Curazao, Donaire, San Martin y muchos países más de Centro y Sur América. Luego de cumplido el contrato con «La Guarachita», la agrupación entra a grabar con la casa Combo Records, de Raffi Car.', aliases = ARRAY[]::text[], occupations = '[]'::jsonb, genres = ARRAY[]::text[], instruments = ARRAY[]::text[] WHERE slug = 'cheche-abreu';

COMMIT;
