BEGIN;

-- Revierte 20260916010300: recrea la ficha manuel-de-jesus-jimenez-ortega, su documento editorial y devuelve los eventos y el alias.

INSERT INTO artists ("id", "name", "sort_name", "type", "birth_year", "death_year", "created_at", "views", "wikidata_id", "first_name", "middle_name", "last_name", "second_last_name", "stage_name", "date_of_birth", "birth_place", "website", "youtube", "facebook", "instagram", "aliases", "mbid", "occupations", "instruments", "genres", "disambiguation", "gender", "ended", "mb_metadata", "updated_at", "province", "slug", "primary_role", "artist_tags", "date_of_death", "status", "primary_genre", "bio_en", "bio_es", "has_image", "image_updated_at", "formation_year", "dissolution_year") SELECT "id", "name", "sort_name", "type", "birth_year", "death_year", "created_at", "views", "wikidata_id", "first_name", "middle_name", "last_name", "second_last_name", "stage_name", "date_of_birth", "birth_place", "website", "youtube", "facebook", "instagram", "aliases", "mbid", "occupations", "instruments", "genres", "disambiguation", "gender", "ended", "mb_metadata", "updated_at", "province", "slug", "primary_role", "artist_tags", "date_of_death", "status", "primary_genre", "bio_en", "bio_es", "has_image", "image_updated_at", "formation_year", "dissolution_year" FROM jsonb_populate_record(NULL::artists, '{"id":"b916e519-f427-45d3-9a42-b5c1ff6d6509","name":"Manuel de Jesús Jiménez Ortega","sort_name":"Jiménez Ortega, Manuel de Jesús","type":"solo_artist","birth_year":1952,"death_year":null,"created_at":"2026-05-24T01:31:51.781Z","views":4,"wikidata_id":null,"first_name":"Manuel","middle_name":"de Jesús","last_name":"Jiménez","second_last_name":"Ortega","stage_name":"Manuel Jiménez","date_of_birth":"1952-10-15T05:00:00.000Z","birth_place":"Cotuí","website":null,"youtube":null,"facebook":null,"instagram":null,"aliases":null,"mbid":null,"occupations":[],"instruments":[],"genres":["bachata","ballads"],"disambiguation":null,"gender":null,"ended":null,"mb_metadata":{},"updated_at":"2026-09-17T11:43:39.014Z","province":"Sánchez Ramírez","slug":"manuel-de-jesus-jimenez-ortega","primary_role":"composer","artist_tags":["secular","legend"],"date_of_death":null,"status":"published","primary_genre":"merengue","bio_en":"Manuel de Jesús Jiménez Ortega is a Dominican musician born in 1952 in Cotuí, the capital of Sánchez Ramírez province, whose work in merengue, bachata, balada, and son reflects a comprehensive engagement with the core genres of Dominican and Caribbean popular music. Cotuí, a city in the central Cibao region, has produced its share of Dominican musical figures, and Jiménez Ortega''s formation there gave him the rhythmic and melodic foundations from which he built a varied career. His engagement with son — the Cuban-rooted genre that underlies much of Caribbean popular music — alongside Dominican styles demonstrates a musician who understood the pan-Caribbean musical dialogue and participated in it actively.","bio_es":null,"has_image":true,"image_updated_at":"2026-07-09T14:00:38.685Z","formation_year":null,"dissolution_year":null}'::jsonb);
INSERT INTO editorial_documents ("id", "document_type", "locale", "schema_version", "document", "status", "owner_artist_id", "created_at", "updated_at", "revision") SELECT "id", "document_type", "locale", "schema_version", "document", "status", "owner_artist_id", "created_at", "updated_at", "revision" FROM jsonb_populate_record(NULL::editorial_documents, '{"id":"179feaa6-03a4-42b9-937d-7bb22b50b409","document_type":"artist_biography","locale":"en","schema_version":1,"document":{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Manuel de Jesús Jiménez Ortega is a Dominican musician born in 1952 in Cotuí, the capital of Sánchez Ramírez province, whose work in merengue, bachata, balada, and son reflects a comprehensive engagement with the core genres of Dominican and Caribbean popular music. Cotuí, a city in the central Cibao region, has produced its share of Dominican musical figures, and Jiménez Ortega''s formation there gave him the rhythmic and melodic foundations from which he built a varied career. His engagement with son — the Cuban-rooted genre that underlies much of Caribbean popular music — alongside Dominican styles demonstrates a musician who understood the pan-Caribbean musical dialogue and participated in it actively.","type":"text"}]}]},"status":"published","owner_artist_id":"b916e519-f427-45d3-9a42-b5c1ff6d6509","created_at":"2026-08-06T02:52:19.958Z","updated_at":"2026-08-06T02:52:19.958Z","revision":1}'::jsonb);
UPDATE artist_view_events SET artist_id = 'b916e519-f427-45d3-9a42-b5c1ff6d6509' WHERE id IN ('e8cd391f-37b8-46a1-b665-7400902384fd', 'b414a927-2cdf-4133-a7ab-c767aabe8ff6', '6868d1c5-2461-4334-b1a3-f7c317624306', '7c820f47-9726-46f2-b225-e2a2371dcbdc');
UPDATE artists SET aliases = array_remove(aliases, 'Manuel de Jesús Jiménez Ortega') WHERE slug = 'manuel-jimenez';

COMMIT;
