BEGIN;

-- Revierte 20260916010200_link_julian_oro_duro.sql

DELETE FROM editorial_entity_references WHERE occurrence_id = '5f2c55f1-3786-4722-9a54-85115cca0505';
UPDATE editorial_documents SET document = '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Yiyo Sarante —Eduardo Sarante, born in 1979 in Baní— is a Dominican salsa singer known as “La Voz de la Salsa”, the voice of salsa. He is the younger brother of the merengue singer Julián Oro Duro.","type":"text"}]},{"type":"paragraph","content":[{"text":"From the congas to the microphone","type":"text","marks":[{"type":"bold"}]}]},{"type":"paragraph","content":[{"text":"He grew up in a musical family, the seventh of nine children, five of whom became musicians. He began as a percussionist and by the age of seven was playing the conga in local orchestras. In 1999 he made his debut as a singer in the tourist area of Bávaro, and in 2003 he joined the orchestra Oro Duro, led by his brother Julián.","type":"text"}]},{"type":"paragraph","content":[{"text":"Solo career","type":"text","marks":[{"type":"bold"}]}]},{"type":"paragraph","content":[{"text":"In 2010, encouraged by his brother and producer José Sarante, he started a solo career and began recording salsa versions of popular songs, among them «Pirata», «Maldita primavera» and «Tierra mala». In 2011 «Tierra mala» reached second place on the annual list of the fifty most played salsa songs in the Dominican Republic, and in 2012 «Maldita primavera» began to be heard on radio in Florida and along the East Coast of the United States. His album «La Voz de la Salsa», with twelve songs, came out in 2013, and he later released «El Álbum». Among his best-known songs are «Me vas a extrañar», «Corazón de acero» and «Mi todo».","type":"text"}]},{"type":"paragraph","content":[{"text":"Recognition","type":"text","marks":[{"type":"bold"}]}]},{"type":"paragraph","content":[{"text":"He won the Premio Soberano for Salsa Performer of the Year in 2014, the year he also played the Festival Presidente, and again in 2025 and 2026.","type":"text"}]},{"type":"paragraph","content":[{"text":"Recent work","type":"text","marks":[{"type":"bold"}]}]},{"type":"paragraph","content":[{"text":"On 31 August 2026 he released a new official video of «Corazón de acero» on his YouTube channel.","type":"text"}]},{"type":"paragraph","content":[{"text":"Legacy","type":"text","marks":[{"type":"bold"}]}]},{"type":"paragraph","content":[{"text":"A 2025 profile on a Mexican salsa radio site described him as one of the leading figures of contemporary salsa.","type":"text"}]}]}'::jsonb, revision = revision - 1, updated_at = now() WHERE id = (SELECT d.id FROM editorial_documents d JOIN artists a ON a.id = d.owner_artist_id WHERE a.slug = 'yiyo-sarante' AND d.locale = 'en' AND d.document_type = 'artist_biography');

DELETE FROM editorial_entity_references WHERE occurrence_id = '021a9430-19f0-46a8-8772-ea479c960cd3';
UPDATE editorial_documents SET document = '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Yiyo Sarante —Eduardo Sarante, nacido en 1979 en Baní— es un cantante dominicano de salsa conocido como “La Voz de la Salsa”. Es hermano menor del cantante de merengue Julián Oro Duro.","type":"text"}]},{"type":"paragraph","content":[{"text":"De las congas al micrófono","type":"text","marks":[{"type":"bold"}]}]},{"type":"paragraph","content":[{"text":"Creció en una familia de músicos, séptimo de nueve hijos, de los cuales cinco se dedicaron a la música. Empezó como percusionista y a los siete años ya tocaba la conga en orquestas locales. En 1999 debutó como cantante en la zona turística de Bávaro, y en 2003 se integró a la orquesta Oro Duro, dirigida por su hermano Julián.","type":"text"}]},{"type":"paragraph","content":[{"text":"Carrera en solitario","type":"text","marks":[{"type":"bold"}]}]},{"type":"paragraph","content":[{"text":"En 2010, animado por su hermano y productor José Sarante, inició su carrera como solista y empezó a grabar versiones en salsa de canciones populares, entre ellas «Pirata», «Maldita primavera» y «Tierra mala». En 2011 «Tierra mala» alcanzó el segundo lugar de la lista anual de las cincuenta canciones de salsa más tocadas de República Dominicana, y en 2012 «Maldita primavera» empezó a sonar en las emisoras de Florida y de la costa este de Estados Unidos. Su álbum «La Voz de la Salsa», de doce canciones, salió en 2013, y más tarde publicó «El Álbum». Entre sus canciones más conocidas figuran «Me vas a extrañar», «Corazón de acero» y «Mi todo».","type":"text"}]},{"type":"paragraph","content":[{"text":"Reconocimiento","type":"text","marks":[{"type":"bold"}]}]},{"type":"paragraph","content":[{"text":"Ganó el Premio Soberano a Salsero del Año en 2014, año en que también actuó en el Festival Presidente, y de nuevo en 2025 y 2026.","type":"text"}]},{"type":"paragraph","content":[{"text":"Trabajo reciente","type":"text","marks":[{"type":"bold"}]}]},{"type":"paragraph","content":[{"text":"El 31 de agosto de 2026 publicó en su canal de YouTube un nuevo video oficial de «Corazón de acero».","type":"text"}]},{"type":"paragraph","content":[{"text":"Legado","type":"text","marks":[{"type":"bold"}]}]},{"type":"paragraph","content":[{"text":"Un perfil de 2025 en un sitio mexicano de radio de salsa lo describió como una de las figuras más importantes de la salsa contemporánea.","type":"text"}]}]}'::jsonb, revision = revision - 1, updated_at = now() WHERE id = (SELECT d.id FROM editorial_documents d JOIN artists a ON a.id = d.owner_artist_id WHERE a.slug = 'yiyo-sarante' AND d.locale = 'es' AND d.document_type = 'artist_biography');

COMMIT;
