BEGIN;

-- La Armada: banda de hardcore punk y metal formada en Santo Domingo en 2001 y radicada en Chicago desde 2008; no un grupo de hip hop y urbano. El relleno hablaba de 'La Armada Roja'. Fuentes: Wikipedia en inglés (historia, discografía, alineaciones; con citas a Vice, Metal Injection, Remezcla, New Noise Magazine, Maximum Rocknroll), Triunfo Rock (29 sep. 2025: originada en Santo Domingo en 2001, radicada en Chicago), Revista Marvin (30 jun. 2021: formada en RD, se mudó a Chicago), YouTube y sitio oficial de la banda, MusicBrainz ('Rock dominicano'; álbum 'Split' sin fecha). Conflicto: una página de Facebook la da formada en 2003; el resto, 2001. Campos: birth_year 2001, birth_place Santo Domingo / Distrito Nacional (formación), primary_genre rock, genres vacío (urbano era erróneo), tag diaspora. La cifra de 'banda de metal más popular de RD según Spotify' no se usa (regla 6).

UPDATE artists SET birth_year = 2001, birth_place = 'Santo Domingo', province = 'Distrito Nacional', genres = ARRAY[]::text[], artist_tags = ARRAY['secular','diaspora']::text[] WHERE slug = 'la-armada';

INSERT INTO editorial_documents (document_type, locale, schema_version, document, status, owner_artist_id, revision)
SELECT 'artist_biography', 'en', 1, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"La Armada is a hardcore punk and metal band formed in Santo Domingo in 2001 and based in Chicago since 2008, which mixes its music with traditional Dominican and Caribbean rhythms and sings in Spanish and English."}]},{"type":"paragraph","content":[{"type":"text","text":"Santo Domingo","marks":[{"type":"bold"}]}]},{"type":"paragraph","content":[{"type":"text","text":"The band began in the capital with the bassist Alberto “Mani” Marte, the drummer Luis Martínez, the guitarists Paúl Rivera and Jonathan Salazar and the singer Javier Fernández. The punk and metal scene of the country was small, so they booked bands and organized shows wherever they could find a space, in abandoned buildings and backyards."}]},{"type":"paragraph","content":[{"type":"text","text":"Chicago","marks":[{"type":"bold"}]}]},{"type":"paragraph","content":[{"type":"text","text":"To find more opportunities as a hardcore band, La Armada relocated to the United States: Marte moved to Florida in 2004 and the rest of the band joined him. In 2006 the band opened for Los Crudos at a Latino punk festival in Chicago, and by 2008 it was based in the city. There it released a self-titled album on Fat Sandwich Records in 2012, the EP «Crisis» in 2014 and «Anti-Colonial Vol. 1» on Creep Records in 2018. Its lyrics deal with colonialism, capitalism, immigration and racism, and the band calls its style “Latino Hardcore Fury”."}]},{"type":"paragraph","content":[{"type":"text","text":"Recent years","marks":[{"type":"bold"}]}]},{"type":"paragraph","content":[{"type":"text","text":"The band had to cancel a European tour because of the COVID-19 pandemic. Javier Fernández left in 2019 and was replaced by the singer Casper Torres, who debuted on the EP «Songs of the Exiled I: Chicago» (2020); the series was dropped and the band released the EP «Opías» in 2021, and in 2022 the album «Anti-Colonial Vol. 2», on Lockjaw Records, Thousand Islands Records and Mal De Ojo Records. Eric Urrea became its drummer, and in September 2024 the single «500 años» introduced Enrique “Quique” Vargas as lead singer. The band has toured with Propagandhi, Iron Chic, Sick of It All and Death by Stereo."}]},{"type":"paragraph","content":[{"type":"text","text":"Legacy","marks":[{"type":"bold"}]}]},{"type":"paragraph","content":[{"type":"text","text":"La Armada is one of the Dominican hardcore bands that built a career abroad, in the punk circuit of Chicago, while keeping its Dominican identity in its language, its themes and its rhythms."}]}]}'::jsonb, 'published', id, 1 FROM artists WHERE slug = 'la-armada'
ON CONFLICT (document_type, owner_artist_id, locale) WHERE document_type = 'artist_biography' DO UPDATE
   SET document = excluded.document, status = 'published', revision = editorial_documents.revision + 1, updated_at = now();
DELETE FROM editorial_entity_references WHERE editorial_document_id IN
  (SELECT d.id FROM editorial_documents d JOIN artists a ON a.id = d.owner_artist_id
    WHERE a.slug = 'la-armada' AND d.locale = 'en' AND d.document_type = 'artist_biography');
UPDATE artists SET bio_en = 'La Armada is a hardcore punk and metal band formed in Santo Domingo in 2001 and based in Chicago since 2008, which mixes its music with traditional Dominican and Caribbean rhythms and sings in Spanish and English.

**Santo Domingo**

The band began in the capital with the bassist Alberto “Mani” Marte, the drummer Luis Martínez, the guitarists Paúl Rivera and Jonathan Salazar and the singer Javier Fernández. The punk and metal scene of the country was small, so they booked bands and organized shows wherever they could find a space, in abandoned buildings and backyards.

**Chicago**

To find more opportunities as a hardcore band, La Armada relocated to the United States: Marte moved to Florida in 2004 and the rest of the band joined him. In 2006 the band opened for Los Crudos at a Latino punk festival in Chicago, and by 2008 it was based in the city. There it released a self-titled album on Fat Sandwich Records in 2012, the EP «Crisis» in 2014 and «Anti-Colonial Vol. 1» on Creep Records in 2018. Its lyrics deal with colonialism, capitalism, immigration and racism, and the band calls its style “Latino Hardcore Fury”.

**Recent years**

The band had to cancel a European tour because of the COVID-19 pandemic. Javier Fernández left in 2019 and was replaced by the singer Casper Torres, who debuted on the EP «Songs of the Exiled I: Chicago» (2020); the series was dropped and the band released the EP «Opías» in 2021, and in 2022 the album «Anti-Colonial Vol. 2», on Lockjaw Records, Thousand Islands Records and Mal De Ojo Records. Eric Urrea became its drummer, and in September 2024 the single «500 años» introduced Enrique “Quique” Vargas as lead singer. The band has toured with Propagandhi, Iron Chic, Sick of It All and Death by Stereo.

**Legacy**

La Armada is one of the Dominican hardcore bands that built a career abroad, in the punk circuit of Chicago, while keeping its Dominican identity in its language, its themes and its rhythms.' WHERE slug = 'la-armada';

INSERT INTO editorial_documents (document_type, locale, schema_version, document, status, owner_artist_id, revision)
SELECT 'artist_biography', 'es', 1, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"La Armada es una banda de hardcore punk y metal formada en Santo Domingo en 2001 y radicada en Chicago desde 2008, que mezcla su música con ritmos tradicionales dominicanos y caribeños y canta en español y en inglés."}]},{"type":"paragraph","content":[{"type":"text","text":"Santo Domingo","marks":[{"type":"bold"}]}]},{"type":"paragraph","content":[{"type":"text","text":"La banda empezó en la capital con el bajista Alberto “Mani” Marte, el baterista Luis Martínez, los guitarristas Paúl Rivera y Jonathan Salazar y el cantante Javier Fernández. La escena punk y metal del país era pequeña, así que organizaban conciertos y reunían bandas donde encontraran espacio, en edificios abandonados y patios."}]},{"type":"paragraph","content":[{"type":"text","text":"Chicago","marks":[{"type":"bold"}]}]},{"type":"paragraph","content":[{"type":"text","text":"Para encontrar más oportunidades como banda de hardcore, La Armada se trasladó a Estados Unidos: Marte se mudó a Florida en 2004 y el resto de la banda se le unió. En 2006 la banda abrió para Los Crudos en un festival de punk latino en Chicago, y en 2008 ya estaba radicada en la ciudad. Allí publicó un álbum homónimo en Fat Sandwich Records en 2012, el EP «Crisis» en 2014 y «Anti-Colonial Vol. 1» en Creep Records en 2018. Sus letras tratan del colonialismo, el capitalismo, la inmigración y el racismo, y la banda llama a su estilo «Latino Hardcore Fury»."}]},{"type":"paragraph","content":[{"type":"text","text":"Años recientes","marks":[{"type":"bold"}]}]},{"type":"paragraph","content":[{"type":"text","text":"La banda tuvo que cancelar una gira europea por la pandemia de COVID-19. Javier Fernández salió en 2019 y fue reemplazado por el cantante Casper Torres, que debutó en el EP «Songs of the Exiled I: Chicago» (2020); la serie se abandonó y la banda publicó el EP «Opías» en 2021, y en 2022 el álbum «Anti-Colonial Vol. 2», en Lockjaw Records, Thousand Islands Records y Mal De Ojo Records. Eric Urrea pasó a ser su baterista, y en septiembre de 2024 el sencillo «500 años» presentó a Enrique “Quique” Vargas como cantante principal. La banda ha girado con Propagandhi, Iron Chic, Sick of It All y Death by Stereo."}]},{"type":"paragraph","content":[{"type":"text","text":"Legado","marks":[{"type":"bold"}]}]},{"type":"paragraph","content":[{"type":"text","text":"La Armada es una de las bandas dominicanas de hardcore que han labrado una carrera en el exterior, en el circuito punk de Chicago, sin perder su identidad dominicana en el idioma, los temas y los ritmos."}]}]}'::jsonb, 'published', id, 1 FROM artists WHERE slug = 'la-armada'
ON CONFLICT (document_type, owner_artist_id, locale) WHERE document_type = 'artist_biography' DO UPDATE
   SET document = excluded.document, status = 'published', revision = editorial_documents.revision + 1, updated_at = now();
DELETE FROM editorial_entity_references WHERE editorial_document_id IN
  (SELECT d.id FROM editorial_documents d JOIN artists a ON a.id = d.owner_artist_id
    WHERE a.slug = 'la-armada' AND d.locale = 'es' AND d.document_type = 'artist_biography');
UPDATE artists SET bio_es = 'La Armada es una banda de hardcore punk y metal formada en Santo Domingo en 2001 y radicada en Chicago desde 2008, que mezcla su música con ritmos tradicionales dominicanos y caribeños y canta en español y en inglés.

**Santo Domingo**

La banda empezó en la capital con el bajista Alberto “Mani” Marte, el baterista Luis Martínez, los guitarristas Paúl Rivera y Jonathan Salazar y el cantante Javier Fernández. La escena punk y metal del país era pequeña, así que organizaban conciertos y reunían bandas donde encontraran espacio, en edificios abandonados y patios.

**Chicago**

Para encontrar más oportunidades como banda de hardcore, La Armada se trasladó a Estados Unidos: Marte se mudó a Florida en 2004 y el resto de la banda se le unió. En 2006 la banda abrió para Los Crudos en un festival de punk latino en Chicago, y en 2008 ya estaba radicada en la ciudad. Allí publicó un álbum homónimo en Fat Sandwich Records en 2012, el EP «Crisis» en 2014 y «Anti-Colonial Vol. 1» en Creep Records en 2018. Sus letras tratan del colonialismo, el capitalismo, la inmigración y el racismo, y la banda llama a su estilo «Latino Hardcore Fury».

**Años recientes**

La banda tuvo que cancelar una gira europea por la pandemia de COVID-19. Javier Fernández salió en 2019 y fue reemplazado por el cantante Casper Torres, que debutó en el EP «Songs of the Exiled I: Chicago» (2020); la serie se abandonó y la banda publicó el EP «Opías» en 2021, y en 2022 el álbum «Anti-Colonial Vol. 2», en Lockjaw Records, Thousand Islands Records y Mal De Ojo Records. Eric Urrea pasó a ser su baterista, y en septiembre de 2024 el sencillo «500 años» presentó a Enrique “Quique” Vargas como cantante principal. La banda ha girado con Propagandhi, Iron Chic, Sick of It All y Death by Stereo.

**Legado**

La Armada es una de las bandas dominicanas de hardcore que han labrado una carrera en el exterior, en el circuito punk de Chicago, sin perder su identidad dominicana en el idioma, los temas y los ritmos.' WHERE slug = 'la-armada';

COMMIT;
